### ISSUE TITLE
Change first day of the week and time format

### ISSUE THREAD

**Issue by svennefenne** [eddiewebb/flarum-calendar#41]
Maybe add an option to change first day of the week to monday. (Euro friendly)

Also maybe add an option to change time format to 24h. (Euro frendly)

**Comment by eddiewebb** [comment]
Of course, I will try to get to this soon!

**Comment by eddiewebb** [comment]
@svennefenne @testm4v3rick - Fixed in `1.5.1`

The plugin now uses Flarum's current locale to pass directly to `fullcalendar`. European locales will change date format and firstDay.

<img width="765" alt="Screen Shot 2022-10-20 at 6 46 57 AM" src="https://user-images.githubusercontent.com/5262154/196929116-9ff831b7-8c52-4de8-8879-f79156770a8b.png">
